### ISSUE TITLE
ReadMe Instructions to Get Demo Running Locally

### ISSUE THREAD

**Issue by nickpoulos** [simeydotme/pokemon-cards-css#32]
First just wanted to say amazing work here, it really is some next-level stuff compared to the stuff you usually see out there. It was so beautiful I had to donate 🔥 🔥 

I am trying to get the demo setup locally, all is working fine out of the box. Except...the actual holo-effects are not loading because the mask files are missing -- because I am having issues getting the `img_scrape.sh` working.  

It seems like there is a missing `REMOTE_JSON` parameter that needs to be given to the script. Potentially from malie.io? Not sure. I found [this old file](https://raw.githubusercontent.com/simeydotme/pokemon-cards-css/150e339e6db28deae7cc0b51868018675b7afdde/public/foils.txt) in this repo, but seems to only direct links to the mask images, and not the foils?  I did not see this parameter mentioned anywhere else in the code.  It is def possible I missed it though!  

The script also seems to reference a local copy of [Real-ERSGAN](https://github.com/xinntao/Real-ESRGAN) that we may want to mention as well. 

I am happy to contribute a PR back to the repo adding some instructions to the ReadMe, but just need some clarification on the REMOTE_JSON stuff above. 

Thanks dude!

**Comment by simeydotme** [comment]
Hi Nick,

Thanks !

riiiight, soo the etch/mask effects are quite complex and I had to do a ton of work to get them running.
I do actually have a the original effects as a fallback, if you provide `mask=""` and `foil=""` to the `<CardProxy />` component, or you simply by-pass the proxy and include the `<Card />` component directly without those props.

The proxy is a helper-component I created because the etching and masks are super complicated (the file naming, API responses, and general chaos of the PTCG conventions), so I needed to modify the naming conventions of files. This proxy helps to align all that.

The etching and mask files are huge (I had to buy a CDN for 16,000+ files hosting and serving), and to make them look good I also had to use the image upscaler you found in the scraper , haha. (nice detective work).

---

So I am not sure what your end-goal is and if masks/etching is important for you, but you have some options;

1) add a `mask=""` and `foil=""` to each `<Card />` component
2) change `App.svelte` to reference directly to `Card.svelte` and not use the proxy (simply change the import statement, and remove the `foil` and `mask` props...
3) send me a DM on Twitter / Email and I should be able to allow you to download the masks/foils as a zip file (it's like over 6gb I think)
4) send me a DM on Twitter / Email and Can give you a link for Malie CDN and help you with scraping yourself
